### ISSUE TITLE
Is it possible to use in secure flag?

### ISSUE THREAD

**Issue by morizyun** [aws/aws-sessionstore-dynamodb-ruby#2]
I really want to use following setting(secure: true), is it possible?

in config/initializers/session_store.rb

`````
YourAppName::Application.config.session_store :dynamodb_store, secure: true
`````

But, unfortunately the result is as follows;

`````
AWS::DynamoDB::Errors::ConditionalCheckFailedException The conditional request failed

AWS::DynamoDB::Errors::ConditionalCheckFailedException (The conditional request failed):
  aws-sdk (1.29.1) lib/aws/core/client.rb:366:in `return_or_raise'
  aws-sdk (1.29.1) lib/aws/core/client.rb:467:in `client_request'
`````

**Comment by awood45** [comment]
Closing with no activity in over a year. Feel free to reopen if you come back to it.

**Comment by morizyun** [comment]
Thanks for your kindness :+1:
